name: belugaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py312h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.4.0
      - aiosignal==1.4.0
      - attrs==25.4.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clingo==5.8.0
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cpmpy==0.10.0
      - cycler==0.12.1
      - deap==1.4.3
      - deprecation==2.1.0
      - didppy==0.10.0
      - dill==0.4.1
      - discrete-optimization==0.5.0
      - dm-tree==0.1.8
      - farama-notifications==0.0.4
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - gymnasium==0.28.1
      - idna==3.11
      - immutabledict==4.2.2
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - lz4==4.3.3
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - minizinc==0.10.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multiprocess==0.70.19
      - networkx==3.6.1
      - numba==0.63.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ortools==9.14.6206
      - pandas==3.0.0
      - pathos==0.3.5
      - pillow==12.1.0
      - plado==0.1.6
      - pox==0.3.7
      - ppft==1.7.8
      - protobuf==6.31.1
      - pyarrow==23.0.0
      - pycparser==3.0
      - pymzn==0.18.3
      - pynng==0.9.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - ray==2.40.0
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-decide==1.0.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sympy==1.13.1
      - tensorboardx==2.6.4
      - torch==2.5.1
      - tqdm==4.67.3
      - triton==3.1.0
      - typing-extensions==4.15.0
      - urllib3==2.6.3
